name: build

on:
  workflow_dispatch:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  checks: write

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: prepare
        env:
          SESSION: ${{ secrets.SESSION }}
          TEMP: /tmp
        run: |
          make prepare y=2024 d=01
          make prepare y=2024 d=02
          make prepare y=2024 d=03
          make prepare y=2024 d=04
          make prepare y=2024 d=05
          make prepare y=2024 d=06
          make prepare y=2024 d=07
      - name: build-and-test
        run: ./gradlew check -Dtestlogger.theme=plain
      - name: test-report
        uses: scacap/action-surefire-report@v1
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
